### ISSUE TITLE
Is this task predicting the next link or any of the links that will occur afterwards?

### ISSUE THREAD

**Issue by zouxiaochuan** [dglai/WSDM2022-Challenge#7]
hello, thank you for hosting such an interesting competition. 
I think most temporal prediction tasks are to predict the next event to happen, but for this challenge it seems to predict the probability of any of the links that will occur between test time intervals. Am i right? because the learning target is different depending on the answer, i want to make it clear.

**Comment by BarclayII** [comment]
Correct.  More precisely, you are to predict whether a link will exist between two nodes within a time interval in the future.  It's not like step-wise forecasting (where you always predict the next event).
